package app

func postgresFreshSchema() []string {
	return []string{
		`CREATE TABLE schema_migrations (
			version BIGINT PRIMARY KEY,
			name VARCHAR(128) NOT NULL,
			applied_at TIMESTAMPTZ NOT NULL
		)`,
		`CREATE TABLE users (
			id VARCHAR(64) PRIMARY KEY,
			email VARCHAR(320) NOT NULL UNIQUE,
			display_name VARCHAR(255) NOT NULL,
			role VARCHAR(16) NOT NULL CHECK(role IN ('admin','user')),
			password_hash VARCHAR(255) NOT NULL,
			two_factor_secret TEXT NOT NULL DEFAULT '',
			two_factor_enabled INTEGER NOT NULL DEFAULT 0,
			disabled INTEGER NOT NULL DEFAULT 0,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE permission_groups (
			id VARCHAR(64) PRIMARY KEY,
			name VARCHAR(255) NOT NULL UNIQUE,
			description TEXT NOT NULL DEFAULT '',
			permissions_json TEXT NOT NULL DEFAULT '[]',
			limits_json TEXT NOT NULL DEFAULT '{"maxAttachmentMb":25,"smtpDailyLimit":200,"smtpMinuteLimit":20,"imapMinuteLimit":200,"pop3MinuteLimit":150}',
			system INTEGER NOT NULL DEFAULT 0,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE user_permission_groups (
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			group_id VARCHAR(64) NOT NULL REFERENCES permission_groups(id) ON DELETE CASCADE,
			created_at VARCHAR(35) NOT NULL,
			PRIMARY KEY(user_id,group_id)
		)`,
		`CREATE INDEX idx_user_permission_groups_group ON user_permission_groups(group_id,user_id)`,
		`CREATE TABLE sessions (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			token_hash VARCHAR(255) NOT NULL UNIQUE,
			expires_at VARCHAR(35) NOT NULL,
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE login_challenges (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			token_hash VARCHAR(255) NOT NULL UNIQUE,
			expires_at VARCHAR(35) NOT NULL,
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE api_tokens (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			name VARCHAR(255) NOT NULL,
			token_hash VARCHAR(255) NOT NULL UNIQUE,
			last_used_at VARCHAR(35),
			expires_at VARCHAR(35) NOT NULL,
			disabled INTEGER NOT NULL DEFAULT 0,
			scopes_json TEXT NOT NULL DEFAULT '["*"]',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_api_tokens_user ON api_tokens(user_id,created_at DESC)`,
		`CREATE INDEX idx_api_tokens_hash ON api_tokens(token_hash)`,
		`CREATE TABLE send_idempotency_keys (
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			idempotency_key VARCHAR(255) NOT NULL,
			request_hash VARCHAR(255) NOT NULL,
			sent_message_id VARCHAR(64) NOT NULL DEFAULT '',
			queue_id VARCHAR(64) NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			PRIMARY KEY(user_id,idempotency_key)
		)`,
		`CREATE INDEX idx_send_idempotency_created ON send_idempotency_keys(created_at)`,
		`CREATE TABLE system_settings (
			key VARCHAR(255) PRIMARY KEY,
			value TEXT NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE mail_templates (
			key VARCHAR(255) PRIMARY KEY,
			name VARCHAR(255) NOT NULL,
			subject TEXT NOT NULL,
			body_text TEXT NOT NULL,
			body_html TEXT NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE domains (
			id VARCHAR(64) PRIMARY KEY,
			name VARCHAR(255) NOT NULL UNIQUE,
			status VARCHAR(32) NOT NULL DEFAULT 'active',
			dkim_selector VARCHAR(255) NOT NULL,
			dkim_public_key TEXT NOT NULL,
			dkim_private_key TEXT NOT NULL,
			dns_status VARCHAR(32) NOT NULL DEFAULT 'unchecked',
			dns_checked_at VARCHAR(35),
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE mailboxes (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			domain_id VARCHAR(64) NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
			local_part VARCHAR(320) NOT NULL,
			address VARCHAR(320) NOT NULL UNIQUE,
			display_name VARCHAR(255) NOT NULL,
			password_hash VARCHAR(255) NOT NULL,
			quota_mb BIGINT NOT NULL DEFAULT 1024,
			status VARCHAR(32) NOT NULL DEFAULT 'active',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			UNIQUE(domain_id,local_part)
		)`,
		`CREATE TABLE mailbox_shares (
			id VARCHAR(64) PRIMARY KEY,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			owner_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			shared_with_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			scope VARCHAR(16) NOT NULL CHECK(scope IN ('all','custom')),
			include_starred INTEGER NOT NULL DEFAULT 0,
			allow_attachments INTEGER NOT NULL DEFAULT 1,
			version BIGINT NOT NULL DEFAULT 1,
			expires_at VARCHAR(35),
			last_accessed_at VARCHAR(35),
			revoked_at VARCHAR(35),
			left_at VARCHAR(35),
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			CHECK(owner_user_id<>shared_with_user_id),
			UNIQUE(mailbox_id,shared_with_user_id)
		)`,
		`CREATE INDEX idx_mailbox_shares_recipient ON mailbox_shares(shared_with_user_id,expires_at,mailbox_id)`,
		`CREATE TABLE mailbox_share_audit_events (
			id VARCHAR(64) PRIMARY KEY,
			share_id VARCHAR(64) NOT NULL REFERENCES mailbox_shares(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			actor_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			event VARCHAR(32) NOT NULL,
			details_json TEXT NOT NULL DEFAULT '{}',
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_mailbox_share_audit_share ON mailbox_share_audit_events(share_id,created_at DESC)`,
		`CREATE TABLE user_notifications (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			type VARCHAR(64) NOT NULL,
			title VARCHAR(255) NOT NULL,
			body TEXT NOT NULL,
			data_json TEXT NOT NULL DEFAULT '{}',
			dedupe_key VARCHAR(255) UNIQUE,
			read_at VARCHAR(35),
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_user_notifications_user ON user_notifications(user_id,created_at DESC)`,
		`CREATE TABLE aliases (
			id VARCHAR(64) PRIMARY KEY,
			domain_id VARCHAR(64) NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
			source VARCHAR(320) NOT NULL UNIQUE,
			destination TEXT NOT NULL,
			enabled INTEGER NOT NULL DEFAULT 1,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE folders (
			id VARCHAR(64) PRIMARY KEY,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			name VARCHAR(255) NOT NULL,
			role VARCHAR(32) NOT NULL,
			sort_order INTEGER NOT NULL DEFAULT 0,
			uid_validity BIGINT NOT NULL DEFAULT 0,
			uid_next BIGINT NOT NULL DEFAULT 1,
			highest_modseq BIGINT NOT NULL DEFAULT 1,
			created_at VARCHAR(35) NOT NULL,
			UNIQUE(mailbox_id,name)
		)`,
		`CREATE TABLE mailbox_share_folders (
			share_id VARCHAR(64) NOT NULL REFERENCES mailbox_shares(id) ON DELETE CASCADE,
			folder_id VARCHAR(64) NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
			PRIMARY KEY(share_id,folder_id)
		)`,
		`CREATE TABLE messages (
			id VARCHAR(64) PRIMARY KEY,
			mailbox_id VARCHAR(64) REFERENCES mailboxes(id) ON DELETE CASCADE,
			folder_id VARCHAR(64) REFERENCES folders(id) ON DELETE CASCADE,
			recipient_addr VARCHAR(320) NOT NULL DEFAULT '',
			message_uid VARCHAR(255) NOT NULL,
			message_id VARCHAR(512) NOT NULL,
			subject TEXT NOT NULL,
			from_addr VARCHAR(320) NOT NULL,
			from_name VARCHAR(255) NOT NULL DEFAULT '',
			to_addrs TEXT NOT NULL,
			cc_addrs TEXT NOT NULL DEFAULT '[]',
			bcc_addrs TEXT NOT NULL DEFAULT '[]',
			sent_at VARCHAR(35) NOT NULL,
			received_at VARCHAR(35) NOT NULL,
			snippet TEXT NOT NULL,
			body_text TEXT NOT NULL,
			body_html TEXT NOT NULL,
			is_read INTEGER NOT NULL DEFAULT 0,
			is_starred INTEGER NOT NULL DEFAULT 0,
			has_attachments INTEGER NOT NULL DEFAULT 0,
			size_bytes BIGINT NOT NULL DEFAULT 0,
			auth_results TEXT NOT NULL DEFAULT '',
			auth_spf VARCHAR(32) NOT NULL DEFAULT 'unknown',
			auth_dkim VARCHAR(32) NOT NULL DEFAULT 'unknown',
			auth_dmarc VARCHAR(32) NOT NULL DEFAULT 'unknown',
			received_spf TEXT NOT NULL DEFAULT '',
			raw_path TEXT NOT NULL DEFAULT '',
			imap_uid BIGINT NOT NULL DEFAULT 0,
			imap_modseq BIGINT NOT NULL DEFAULT 1,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_messages_mailbox_folder_received_id ON messages(mailbox_id,folder_id,received_at DESC,id DESC)`,
		`CREATE INDEX idx_messages_received_id ON messages(received_at DESC,id DESC)`,
		`CREATE INDEX idx_messages_mailbox_received_id ON messages(mailbox_id,received_at DESC,id DESC)`,
		`CREATE INDEX idx_messages_folder_read ON messages(folder_id,is_read)`,
		`CREATE INDEX idx_messages_mailbox_starred_received_id ON messages(mailbox_id,received_at DESC,id DESC) WHERE is_starred=1`,
		`CREATE INDEX idx_messages_mailbox_message_id ON messages(mailbox_id,message_id) WHERE message_id<>''`,
		`CREATE UNIQUE INDEX idx_messages_mailbox_raw_path ON messages(mailbox_id,md5(raw_path)) WHERE raw_path<>'' AND mailbox_id IS NOT NULL`,
		`CREATE UNIQUE INDEX idx_messages_unregistered_raw_path ON messages(md5(raw_path)) WHERE raw_path<>'' AND mailbox_id IS NULL`,
		`CREATE INDEX idx_messages_maildir_backfill ON messages(created_at) WHERE raw_path='' AND mailbox_id IS NOT NULL AND mailbox_id<>'' AND folder_id IS NOT NULL AND folder_id<>''`,
		`CREATE INDEX idx_messages_maildir_cleanup ON messages(updated_at) WHERE raw_path<>'' AND mailbox_id IS NOT NULL AND mailbox_id<>''`,
		`CREATE UNIQUE INDEX idx_messages_folder_imap_uid ON messages(folder_id,imap_uid) WHERE folder_id IS NOT NULL AND imap_uid>0`,
		`CREATE TABLE sent_message_dedupe_keys (
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			folder_id VARCHAR(64) NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
			message_id VARCHAR(512) NOT NULL,
			created_at VARCHAR(35) NOT NULL,
			PRIMARY KEY(mailbox_id,folder_id,message_id)
		)`,
		`CREATE TABLE send_as_grants (
			id VARCHAR(64) PRIMARY KEY,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			address VARCHAR(320) NOT NULL,
			display_name VARCHAR(255) NOT NULL DEFAULT '',
			enabled INTEGER NOT NULL DEFAULT 1,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			UNIQUE(mailbox_id,address)
		)`,
		`CREATE TABLE send_queue (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			sent_message_id VARCHAR(64) NOT NULL DEFAULT '',
			message_id VARCHAR(512) NOT NULL DEFAULT '',
			source VARCHAR(64) NOT NULL,
			mail_from VARCHAR(320) NOT NULL,
			header_from VARCHAR(320) NOT NULL,
			recipients_json TEXT NOT NULL,
			mime_base64 TEXT NOT NULL,
			status VARCHAR(32) NOT NULL DEFAULT 'queued',
			attempt_count INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 5,
			next_attempt_at VARCHAR(35) NOT NULL,
			last_error TEXT NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			delivered_at VARCHAR(35)
		)`,
		`CREATE INDEX idx_send_queue_due ON send_queue(status,next_attempt_at,created_at)`,
		`CREATE UNIQUE INDEX idx_send_queue_mailbox_source_message_id ON send_queue(mailbox_id,source,message_id) WHERE message_id<>''`,
		`CREATE TABLE send_audit_events (
			id VARCHAR(64) PRIMARY KEY,
			queue_id VARCHAR(64) NOT NULL DEFAULT '',
			user_id VARCHAR(64) NOT NULL DEFAULT '',
			mailbox_id VARCHAR(64) NOT NULL DEFAULT '',
			sent_message_id VARCHAR(64) NOT NULL DEFAULT '',
			source VARCHAR(64) NOT NULL,
			event VARCHAR(64) NOT NULL,
			status VARCHAR(32) NOT NULL,
			mail_from VARCHAR(320) NOT NULL DEFAULT '',
			header_from VARCHAR(320) NOT NULL DEFAULT '',
			recipients_json TEXT NOT NULL DEFAULT '[]',
			error TEXT NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_send_audit_events_created_id ON send_audit_events(created_at DESC,id DESC)`,
		`CREATE INDEX idx_send_audit_events_mailbox_created_id ON send_audit_events(mailbox_id,created_at DESC,id DESC)`,
		`CREATE INDEX idx_send_audit_events_event_created_id ON send_audit_events(event,created_at DESC,id DESC)`,
		`CREATE INDEX idx_send_audit_events_queue_created_id ON send_audit_events(queue_id,created_at,id)`,
		`CREATE TABLE delivery_events (
			id VARCHAR(64) PRIMARY KEY,
			external_id VARCHAR(255) NOT NULL,
			provider VARCHAR(64) NOT NULL,
			queue_id VARCHAR(64) NOT NULL REFERENCES send_queue(id) ON DELETE CASCADE,
			sent_message_id VARCHAR(64) NOT NULL DEFAULT '',
			rfc_message_id VARCHAR(512) NOT NULL DEFAULT '',
			recipient VARCHAR(320) NOT NULL,
			status VARCHAR(64) NOT NULL,
			reason TEXT NOT NULL DEFAULT '',
			occurred_at VARCHAR(35) NOT NULL,
			created_at VARCHAR(35) NOT NULL,
			UNIQUE(provider,external_id)
		)`,
		`CREATE INDEX idx_delivery_events_message ON delivery_events(sent_message_id,occurred_at,id)`,
		`CREATE INDEX idx_delivery_events_rfc_message ON delivery_events(rfc_message_id,occurred_at,id)`,
		`CREATE TABLE status_webhook_outbox (
			id VARCHAR(64) PRIMARY KEY,
			event_key VARCHAR(255) NOT NULL UNIQUE,
			event_type VARCHAR(64) NOT NULL,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			payload_json TEXT NOT NULL,
			attempt_count INTEGER NOT NULL DEFAULT 0,
			next_attempt_at VARCHAR(35) NOT NULL,
			last_error TEXT NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			delivered_at VARCHAR(35)
		)`,
		`CREATE INDEX idx_status_webhook_outbox_due ON status_webhook_outbox(delivered_at,next_attempt_at,created_at)`,
		`CREATE INDEX idx_status_webhook_outbox_mailbox ON status_webhook_outbox(mailbox_id,created_at)`,
		`CREATE TABLE attachments (
			id VARCHAR(64) PRIMARY KEY,
			message_id VARCHAR(64) NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
			filename VARCHAR(512) NOT NULL,
			content_type VARCHAR(255) NOT NULL,
			size_bytes BIGINT NOT NULL,
			storage_path TEXT NOT NULL,
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_attachments_message_filename ON attachments(message_id,filename)`,
		`CREATE TABLE scheduled_sends (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			draft_id VARCHAR(64) REFERENCES messages(id) ON DELETE SET NULL,
			payload_json TEXT NOT NULL,
			send_at VARCHAR(35) NOT NULL,
			status VARCHAR(32) NOT NULL DEFAULT 'pending',
			error TEXT NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			sent_at VARCHAR(35)
		)`,
		`CREATE INDEX idx_scheduled_sends_due ON scheduled_sends(status,send_at)`,
		`CREATE TABLE smtp_send_events (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_smtp_send_events_user_created ON smtp_send_events(user_id,created_at)`,
		`CREATE TABLE imap_events (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_imap_events_user_created ON imap_events(user_id,created_at)`,
		`CREATE TABLE pop3_events (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			created_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_pop3_events_user_created ON pop3_events(user_id,created_at)`,
		`CREATE TABLE external_imap_accounts (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			name VARCHAR(255) NOT NULL,
			host VARCHAR(255) NOT NULL,
			port INTEGER NOT NULL,
			tls_mode VARCHAR(16) NOT NULL CHECK(tls_mode IN ('tls','starttls','plain')),
			username VARCHAR(320) NOT NULL,
			password_ciphertext TEXT NOT NULL,
			auth_mode VARCHAR(16) NOT NULL DEFAULT 'password' CHECK(auth_mode IN ('password','oauth2')),
			oauth_provider VARCHAR(64) NOT NULL DEFAULT '',
			oauth_email VARCHAR(320) NOT NULL DEFAULT '',
			oauth_access_token_ciphertext TEXT NOT NULL DEFAULT '',
			oauth_refresh_token_ciphertext TEXT NOT NULL DEFAULT '',
			oauth_expiry VARCHAR(35),
			storage_mode VARCHAR(16) NOT NULL DEFAULT 'local' CHECK(storage_mode IN ('local','remote')),
			sync_read_state INTEGER NOT NULL DEFAULT 1,
			enabled INTEGER NOT NULL DEFAULT 1,
			last_sync_at VARCHAR(35),
			last_status VARCHAR(32) NOT NULL DEFAULT 'idle',
			last_error TEXT NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_external_imap_accounts_user_mailbox ON external_imap_accounts(user_id,mailbox_id)`,
		`CREATE INDEX idx_external_imap_accounts_enabled ON external_imap_accounts(enabled,updated_at)`,
		`CREATE TABLE external_imap_folder_states (
			account_id VARCHAR(64) NOT NULL REFERENCES external_imap_accounts(id) ON DELETE CASCADE,
			remote_folder VARCHAR(255) NOT NULL,
			local_folder_id VARCHAR(64) NOT NULL DEFAULT '',
			uid_validity BIGINT NOT NULL DEFAULT 0,
			last_uid BIGINT NOT NULL DEFAULT 0,
			last_sync_at VARCHAR(35),
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			PRIMARY KEY(account_id,remote_folder)
		)`,
		`CREATE TABLE external_imap_messages (
			account_id VARCHAR(64) NOT NULL REFERENCES external_imap_accounts(id) ON DELETE CASCADE,
			remote_folder VARCHAR(255) NOT NULL,
			uid_validity BIGINT NOT NULL,
			uid BIGINT NOT NULL,
			message_id VARCHAR(512) NOT NULL DEFAULT '',
			local_message_id VARCHAR(64) NOT NULL DEFAULT '',
			is_read INTEGER NOT NULL DEFAULT 0,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			PRIMARY KEY(account_id,remote_folder,uid_validity,uid)
		)`,
		`CREATE INDEX idx_external_imap_messages_local ON external_imap_messages(local_message_id) WHERE local_message_id<>''`,
		`CREATE TABLE external_imap_sync_runs (
			id VARCHAR(64) PRIMARY KEY,
			account_id VARCHAR(64) NOT NULL REFERENCES external_imap_accounts(id) ON DELETE CASCADE,
			folder VARCHAR(255) NOT NULL DEFAULT '',
			status VARCHAR(32) NOT NULL,
			imported INTEGER NOT NULL DEFAULT 0,
			skipped INTEGER NOT NULL DEFAULT 0,
			failed INTEGER NOT NULL DEFAULT 0,
			error TEXT NOT NULL DEFAULT '',
			started_at VARCHAR(35) NOT NULL,
			finished_at VARCHAR(35)
		)`,
		`CREATE INDEX idx_external_imap_sync_runs_account_started ON external_imap_sync_runs(account_id,started_at DESC)`,
		`CREATE TABLE contacts (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			name VARCHAR(255) NOT NULL,
			email VARCHAR(320) NOT NULL,
			note TEXT NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			UNIQUE(user_id,email)
		)`,
		`CREATE INDEX idx_contacts_user ON contacts(user_id,email)`,
		`CREATE TABLE mail_signatures (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL DEFAULT '',
			name VARCHAR(255) NOT NULL,
			content TEXT NOT NULL,
			is_default INTEGER NOT NULL DEFAULT 0,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_mail_signatures_user_mailbox ON mail_signatures(user_id,mailbox_id,is_default)`,
		`CREATE TABLE mail_rules (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL DEFAULT '',
			name VARCHAR(255) NOT NULL,
			match_mode VARCHAR(16) NOT NULL DEFAULT 'all',
			conditions_json TEXT NOT NULL DEFAULT '[]',
			actions_json TEXT NOT NULL DEFAULT '[]',
			from_contains TEXT NOT NULL DEFAULT '',
			subject_contains TEXT NOT NULL DEFAULT '',
			action VARCHAR(64) NOT NULL,
			apply_to_existing INTEGER NOT NULL DEFAULT 0,
			stop_processing INTEGER NOT NULL DEFAULT 0,
			enabled INTEGER NOT NULL DEFAULT 1,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE INDEX idx_mail_rules_user_mailbox ON mail_rules(user_id,mailbox_id,enabled)`,
		`CREATE TABLE blocked_senders (
			id VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			mailbox_id VARCHAR(64) NOT NULL DEFAULT '',
			email VARCHAR(320) NOT NULL,
			reason TEXT NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			UNIQUE(user_id,mailbox_id,email)
		)`,
		`CREATE INDEX idx_blocked_senders_user_mailbox ON blocked_senders(user_id,mailbox_id,email)`,
		`CREATE TABLE mail_labels (
			id VARCHAR(64) PRIMARY KEY,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			name VARCHAR(255) NOT NULL,
			color VARCHAR(32) NOT NULL DEFAULT '#64748b',
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			UNIQUE(mailbox_id,name)
		)`,
		`CREATE TABLE mailbox_share_labels (
			share_id VARCHAR(64) NOT NULL REFERENCES mailbox_shares(id) ON DELETE CASCADE,
			label_id VARCHAR(64) NOT NULL REFERENCES mail_labels(id) ON DELETE CASCADE,
			PRIMARY KEY(share_id,label_id)
		)`,
		`CREATE INDEX idx_mail_labels_mailbox ON mail_labels(mailbox_id,name)`,
		`CREATE TABLE message_labels (
			message_id VARCHAR(64) NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
			label_id VARCHAR(64) NOT NULL REFERENCES mail_labels(id) ON DELETE CASCADE,
			created_at VARCHAR(35) NOT NULL,
			PRIMARY KEY(message_id,label_id)
		)`,
		`CREATE INDEX idx_message_labels_label ON message_labels(label_id,message_id)`,
		`CREATE TABLE telegram_bindings (
			chat_id BIGINT PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			is_admin_target INTEGER NOT NULL DEFAULT 0,
			created_at VARCHAR(35) NOT NULL,
			updated_at VARCHAR(35) NOT NULL,
			UNIQUE(user_id)
		)`,
		`CREATE TABLE telegram_binding_codes (
			code VARCHAR(64) PRIMARY KEY,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			chat_id BIGINT NOT NULL,
			expires_at VARCHAR(35) NOT NULL,
			used_at VARCHAR(35) NOT NULL DEFAULT ''
		)`,
		`CREATE INDEX idx_telegram_binding_codes_user ON telegram_binding_codes(user_id)`,
		`CREATE TABLE telegram_notify_outbox (
			id VARCHAR(64) PRIMARY KEY,
			mailbox_id VARCHAR(64) NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
			user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			message_id VARCHAR(64) NOT NULL,
			chat_id BIGINT NOT NULL,
			subject TEXT NOT NULL,
			from_addr VARCHAR(320) NOT NULL,
			from_name TEXT NOT NULL DEFAULT '',
			snippet TEXT NOT NULL DEFAULT '',
			dedupe_key VARCHAR(255) NOT NULL,
			attempt_count INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 5,
			next_attempt_at VARCHAR(35) NOT NULL,
			delivered_at VARCHAR(35) NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			UNIQUE(dedupe_key)
		)`,
		`CREATE INDEX idx_telegram_notify_outbox_due ON telegram_notify_outbox(delivered_at,next_attempt_at,created_at)`,
		`CREATE TABLE telegram_mailbox_settings (
			mailbox_id VARCHAR(64) PRIMARY KEY,
			notify_enabled INTEGER NOT NULL DEFAULT 1,
			notify_spam INTEGER NOT NULL DEFAULT 0,
			updated_at VARCHAR(35) NOT NULL
		)`,
		`CREATE TABLE telegram_alert_outbox (
			id VARCHAR(64) PRIMARY KEY,
			alert_type VARCHAR(64) NOT NULL,
			chat_id BIGINT NOT NULL,
			title TEXT NOT NULL,
			body TEXT NOT NULL DEFAULT '',
			dedupe_key VARCHAR(255) NOT NULL,
			attempt_count INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 5,
			next_attempt_at VARCHAR(35) NOT NULL,
			delivered_at VARCHAR(35) NOT NULL DEFAULT '',
			created_at VARCHAR(35) NOT NULL,
			UNIQUE(dedupe_key)
		)`,
		`CREATE INDEX idx_telegram_alert_outbox_due ON telegram_alert_outbox(delivered_at,next_attempt_at,created_at)`,
	}
}
